import imageList from "./imageList";


    const studentList = [
      {
        "id": 1,
        "face": imageList.claude,
        "crestIcon": [imageList.riegan],
        "name": "Claude",
        "age": 17,
        "likes": ["tactics", "schemes", "parties"],
        "crest": "Minor Crest of Riegan",
        "crestEffect": "Restores HP equal to 30% of damage dealt when using combat arts.",
        "color": "yellow",
        "favSubjects": ["Bows", "Flying", "Swords", "Horse Riding", "Tactics", "Axes??"],
        "house": "Golden Deer"
      },
      {
        "id": 2,
        "face": imageList.leonie,
        "crestIcon": [""],
        "name": "Leonie",
        "age": 19,
        "likes": ["saving money", "bow maintenance", "CAPTAIN JERALT"],
        "crest": "none",
        "crestEffect": "CAPTAIN JERALT > crest",
        "color": "orange",
        "favSubjects": ["Bows", "Lances", "Horse Riding"],
        "house": "Golden Deer"
      },
      {
        "id": 3,
        "face": imageList.hapi,
        "crestIcon": [imageList.timotheos],
        "name": "Hapi",
        "age": 20,
        "likes": ["pretty stones", "star gazing", "nicknames"],
        "crest": "Minor Crest of Timotheos",
        "crestEffect": "Conserves uses of recovery magic.",
        "color": "green",
        "favSubjects": ["Dark Magic", "Flying", "Horse Riding", "Axes??"],
        "house": "Ashen Wolves"
      },
      {
        "id": 4,
        "face": imageList.lysithea,
        "crestIcon": [imageList.gloucester, imageList.charon],
        "name": "Lysithea",
        "age": 15,
        "likes": ["sweets", "magic research", "studying"],
        "crest": "Major Crest of Gloucester / Minor Crest of Charon",
        "crestEffect": "Raises Might by 5 during magic attacks.  /  Raises Might when using combat arts.",
        "color": "silver",
        "favSubjects": ["Dark Magic", "White Magic", "Tactics", "Swords??"],
        "house": "Golden Deer"
      },
      {
        "id": 5,
        "face": imageList.sylvain,
        "crestIcon": [imageList.gautier],
        "name": "Sylvain",
        "age": 19,
        "likes": ["art and theater", "flirting", "taking it easy"],
        "crest": "Minor Crest of Gautier",
        "crestEffect": "Raises Might by 5 when using combat arts.",
        "color": "gray",
        "favSubjects": ["Lances", "Axes", "Horse Riding", "Black Magic??"],
        "house": "Blue Lions"
      },
      {
        "id": 6,
        "face": imageList.hilda,
        "crestIcon": [imageList.goneril],
        "name": "Hilda",
        "age": 18,
        "likes": ["chatting", "omg! accessories!", "like, taking it easy and stuff"],
        "crest": "Minor Crest of Goneril",
        "crestEffect": "Prevents enemy counterattacks when using combat arts.",
        "color": "pink",
        "favSubjects": ["Axes", "Lances", "Armor??"],
        "house": "Golden Deer"
      },
      {
        "id": 7,
        "face": imageList.caspar,
        "crestIcon": [""],
        "name": "Caspar",
        "age": 16,
        "likes": ["training", "quick meals", "よっしゃ〜！いくぜぇ！"],
        "crest": "none",
        "crestEffect": "Right makes might, right?",
        "color": "aquamarine",
        "favSubjects": ["Gauntlets", "Axes"],
        "house": "Black Eagles"
      },
      {
        "id": 8,
        "face": imageList.balthus,
        "crestIcon": [imageList.chevalier],
        "name": "Balthus",
        "age": 26,
        "likes": ["brawling", "adventure", "punching beasts", "older women"],
        "crest": "Major Crest of Chevalier",
        "crestEffect": "Restores HP equal to 30% of damage dealt when using combat arts.",
        "color": "brown",
        "favSubjects": ["Gauntlets", "Axes", "Swords", "Armor", "White Magic", "Black Magic??"],
        "house": "Ashen Wolves"
      },
      {
        "id": 9,
        "face": imageList.edelgard,
        "crestIcon": [imageList.flames, imageList.seiros],
        "name": "Edelgard",
        "age": 17,
        "likes": ["reading", "political history", "solitary exploring"],
        "crest": "Major Crest of Flames / Minor Crest of Seiros",
        "crestEffect": "Restores HP equal to 30% of damage dealt when using weapons, combat arts or attack magic. Also has a roughly 1 in 4 chance to raise Might by 5 and prevent counterattacks.  /  Raises Might by 5 when using combat arts.",
        "color": "darkred",
        "favSubjects": ["Axes", "Swords", "Armor", "Tactics", "Dark Magic??"],
        "house": "Black Eagles"
      },
      {
        "id": 10,
        "face": imageList.dimitri,
        "crestIcon": [imageList.blaiddyd],
        "name": "Dimitri",
        "age": 17,
        "likes": ["training", "weapon maintenance", "Dedue"],
        "crest": "Minor Crest of Blaiddyd",
        "crestEffect": "Doubles Attack and weapon uses for combat arts.",
        "color": "blue",
        "favSubjects": ["Swords", "Lances", "Tactics", "Horse Riding??"],
        "house": "Blue Lions"
      },
      {
        "id": 11,
        "face": imageList.petra,
        "crestIcon": [""],
        "name": "Petra",
        "age": 15,
        "likes": ["hunting", "studying", "swimming"],
        "crest": "none",
        "crestEffect": "I am not having a crest.",
        "color": "mauve",
        "favSubjects": ["The Swords", "The Axes", "The Bows", "The Flying"],
        "house": "Black Eagles"
      },
      {
        "id": 12,
        "face": imageList.constance,
        "crestIcon": [imageList.noa],
        "name": "Constance",
        "age": 18,
        "likes": ["magic research", "social advancement", "people who do as they're told"],
        "crest": "Major Crest of Noa",
        "crestEffect": "Conserves uses of attack magic.",
        "color": "pink",
        "favSubjects": ["Swords", "Black Magic", "White Magic", "Flying", "Tactics", "Gauntlets??"],
        "house": "Ashen Wolves"
      },
      {
        "id": 13,
        "face": imageList.hubert,
        "crestIcon": [""],
        "name": "Hubert",
        "age": 20,
        "likes": ["strategy and tactics", "Lady Edelgard"],
        "crest": "none",
        "crestEffect": "-",
        "color": "darkgray",
        "favSubjects": ["Bows", "Dark Magic", "Tactics", "Lances??"],
        "house": "Black Eagles"
      },
      {
        "id": 14,
        "face": imageList.dedue,
        "crestIcon": [""],
        "name": "Dedue",
        "age": 18,
        "likes": ["Dimitri", "gardening", "cooking"],
        "crest": "none",
        "crestEffect": "-",
        "color": "brown",
        "favSubjects": ["Gauntlets", "Armor", "Axes", "Lances"],
        "house": "Blue Lions"
      },
      {
        "id": 15,
        "face": imageList.flayn,
        "crestIcon": [imageList.cethleann],
        "name": "Flayn",
        "age": "??",
        "likes": ["Making friends", "fish!"],
        "crest": "Major Crest of Cethleann",
        "crestEffect": "Raises Might by 5 when using recovery magic.",
        "color": "lightgreen",
        "favSubjects": ["White Magic", "Lances", "Black Magic??"],
        "house": "Garreg Mach"
      },
      {
        "id": 16,
        "face": imageList.ignatz,
        "crestIcon": [""],
        "name": "Ignatz",
        "age": 17,
        "likes": ["painting", "beautiful views", "people pleasing"],
        "crest": "none",
        "crestEffect": "-",
        "color": "yellow",
        "favSubjects": ["Swords", "Bows", "Tactics", "Black Magic??"],
        "house": "Golden Deer"
      },
      {
        "id": 17,
        "face": imageList.linhardt,
        "crestIcon": [imageList.cethleann],
        "name": "Linhardt",
        "age": 16,
        "likes": ["sleeping", "crest research", "fishing"],
        "crest": "Minor Crest of Cethleann",
        "crestEffect": "Raises Might by 5 when using recovery magic.",
        "color": "green",
        "favSubjects": ["White Magic", "Black Magic"],
        "house": "Black Eagles"
      },
      {
        "id": 18,
        "face": imageList.ashe,
        "crestIcon": [""],
        "name": "Ashe",
        "age": 16,
        "likes": ["reading", "cooking", "knighthood"],
        "crest": "none",
        "crestEffect": "-",
        "color": "gray",
        "favSubjects": ["Bows", "Axes", "Lances??"],
        "house": "Blue Lions"
      },
      {
        "id": 19,
        "face": imageList.cyril,
        "crestIcon": [""],
        "name": "Cyril",
        "age": 14,
        "likes": ["napping", "cleaning", "Lady Rhea"],
        "crest": "none",
        "crestEffect": "-",
        "color": "tan",
        "favSubjects": ["Bows", "Axes", "Lances", "Horse Riding", "Flying"],
        "house": "Garreg Mach"
      },
      {
        "id": 20,
        "face": imageList.ingrid,
        "crestIcon": [imageList.daphnel],
        "name": "Ingrid",
        "age": 17,
        "likes": ["eating", "reading", "knighthood"],
        "crest": "Minor Crest of Daphnel",
        "crestEffect": "Raises Might by 5 when using combat arts.",
        "color": "blue",
        "favSubjects": ["Swords", "Lances", "Horse Riding", "Flying"],
        "house": "Blue Lions"
      },
      {
        "id": 21,
        "face": imageList.dorothea,
        "crestIcon": [""],
        "name": "Dorothea",
        "age": 18,
        "likes": ["singing", "a bit of everything"],
        "crest": "none",
        "crestEffect": "<3",
        "color": "crimson",
        "favSubjects": ["Swords", "Black Magic", "White Magic??"],
        "house": "Black Eagles"
      },
      {
        "id": 22,
        "face": imageList.yuri,
        "crestIcon": [imageList.aubin],
        "name": "Yuri",
        "age": 20,
        "likes": ["cooking", "schemes", "mom"],
        "crest": "Major Crest of Aubin",
        "crestEffect": "Prevents enemy counterattacks when using a weapon.",
        "color": "periwinkle",
        "favSubjects": ["Swords", "Black Magic", "White Magic", "Tactics", "Bows??"],
        "house": "Ashen Wolves"
      },
      {
        "id": 23,
        "face": imageList.ferdinand,
        "crestIcon": [imageList.cichol],
        "name": "Ferdinand",
        "age": 17,
        "likes": ["nobility", "collecting weapons", "theater", "I AM FERDINAND VON AEGIR"],
        "crest": "Minor Crest of Cichol",
        "crestEffect": "Prevents enemy counterattacks when using combat arts.",
        "color": "red",
        "favSubjects": ["Swords", "Lances", "Axes", "Horse Riding", "Armor??"],
        "house": "Black Eagles"
      },
      {
        "id": 24,
        "face": imageList.lorenz,
        "crestIcon": [imageList.gloucester],
        "name": "Lorenz",
        "age": 18,
        "likes": ["nobility", "tea", "thinking about the future of the alliance"],
        "crest": "Minor Crest of Gloucester",
        "crestEffect": "Raises Might by 5 during magic attacks.",
        "color": "blue",
        "favSubjects": ["Lances", "Black Magic", "Horse Riding"],
        "house": "Golden Deer"
      },
      {
        "id": 25,
        "face": imageList.bernadetta,
        "crestIcon": [imageList.indech],
        "name": "Bernadetta",
        "age": 17,
        "likes": ["knitting and embroidery", "drawing", "fan fics"],
        "crest": "Minor Crest of Indech",
        "crestEffect": "Strike twice when using a weapon.",
        "color": "purple",
        "favSubjects": ["Lances", "Bows", "Horse Riding??"],
        "house": "Black Eagles"
      },
      {
        "id": 26,
        "face": imageList.annette,
        "crestIcon": [imageList.dominic],
        "name": "Annette",
        "age": 16,
        "likes": ["studying", "singing", "dancing"],
        "crest": "Minor Crest of Dominic",
        "crestEffect": "Conserves uses of attack magic.",
        "color": "orange",
        "favSubjects": ["Axes", "Black Magic", "Tactics"],
        "house": "Blue Lions"
      },
      {
        "id": 27,
        "face": imageList.marianne,
        "crestIcon": [imageList.the_beast],
        "name": "Marianne",
        "age": 17,
        "likes": ["praying", "animals"],
        "crest": "Minor Crest of the Beast",
        "crestEffect": "Raises Might by 5 when using a weapon.",
        "color": "lightblue",
        "favSubjects": ["Swords", "White Magic", "Horse Riding", "Flying", "Lances??"],
        "house": "Golden Deer"
      },
      {
        "id": 28,
        "face": imageList.felix,
        "crestIcon": [imageList.fraldarius],
        "name": "Felix",
        "age": 17,
        "likes": ["swords", "training", "teenage angst"],
        "crest": "Major Crest of Fraldarius",
        "crestEffect": "Raises Might by 5 when using a weapon.",
        "color": "gray",
        "favSubjects": ["Swords", "Gauntlets", "Bows", "Black Magic??"],
        "house": "Blue Lions"
      },
      {
        "id": 29,
        "face": imageList.raphael,
        "crestIcon": [""],
        "name": "Raphael",
        "age": 18,
        "likes": ["strength training", "eating", "his sister"],
        "crest": "none",
        "crestEffect": "-",
        "color": "wheat",
        "favSubjects": ["Axes", "Gauntlets", "Armor"],
        "house": "Golden Deer"
      },
      {
        "id": 30,
        "face": imageList.mercedes,
        "crestIcon": [imageList.lamine],
        "name": "Mercedes",
        "age": 22,
        "likes": ["praying", "baking"],
        "crest": "Minor Crest of Lamine",
        "crestEffect": "Conserves uses of recovery magic.",
        "color": "beige",
        "favSubjects": ["Black Magic", "White Magic", "Bows??"],
        "house": "Blue Lions"
      }
    ];

    const teacherList = [
        {
          "id": 100,
          "face": imageList.shamir,
          "crestIcon": [""],
          "name": "Shamir",
          "age": 25,
          "likes": ["silence", "telling it like it is"],
          "crest": "none",
          "crestEffect": "...",
          "color": "purple",
          "courses": ["Sit down, Shut up, and Snipe", "How to Breathe", "Foreign Bow Techniques"],
          "house": "Garreg Mach"
        },
        {
          "id": 101,
          "face": imageList.jeritza,
          "crestIcon": [imageList.lamine],
          "name": "Jeritza",
          "age": 21,
          "likes": ["sweets", "definitely not socializing"],
          "crest": "Minor Crest of Lamine",
          "crestEffect": "Conserves uses of recovery magic.",
          "color": "wheat",
          "courses": ["Fight me", "Dueling 101", "Relishing in the blood of your enemies"],
          "house": "Garreg Mach"
        },
        {
          "id": 102,
          "face": imageList.hanneman,
          "crestIcon": [imageList.indech],
          "name": "Hanneman",
          "age": 51,
          "likes": ["crests", "crest research", "monocles"],
          "crest": "Minor Crest of Indech",
          "crestEffect": "Strike twice when using a weapon.",
          "color": "tan",
          "courses": ["The Physical Mage: How to Incorporate Bow Techniques into your training", "Fire from your Fingertips: A Magic Introduction", "Leveraging Crest Power"],
          "house": "Garreg Mach"
        },
        {
          "id": 103,
          "face": imageList.catherine,
          "crestIcon": [imageList.charon],
          "name": "Catherine",
          "age": 27,
          "likes": ["Lady Rhea", "strong opponents", "defending Lady Rhea"],
          "crest": "Major Crest of Charon",
          "crestEffect": "Raises Might when using combat arts.",
          "color": "red",
          "courses": ["Advanced Sword Techniques", "Just Punch the Guy: What to do when Disarmed", "Philosophy 101: Why Seiros is Always Right"],
          "house": "Garreg Mach"
        },
        {
          "id": 104,
          "face": imageList.alois,
          "crestIcon": [""],
          "name": "Alois",
          "age": 44,
          "likes": ["dad jokes", "fishing", "collecting old coins"],
          "crest": "none",
          "crestEffect": "I have not come *ACRESS* *A CREST*!",
          "color": "blue",
          "courses": ["Axing Questions about Axes: How to Axentuate your Axe Skills", "Gon' Let you Use some Gauntlets: Fisticuffs 101", "Advanced Fishing"],
          "house": "Garreg Mach"
        },
        {
          "id": 105,
          "face": imageList.byleth,
          "crestIcon": [imageList.flames],
          "name": "Byleth",
          "age": 20,
          "likes": ["...", "....", "....."],
          "crest": "Major Crest of Flames",
          "crestEffect": "Restores HP equal to 30% of damage dealt when using weapons, combat arts or attack magic. Also has a roughly 1 in 4 chance to raise Might by 5 and prevent counterattacks.",
          "color": "cyan",
          "courses": ["Fishing 101", "Practical Battlefield Knowledge", "Intro to Cooking"],
          "house": "Garreg Mach"
        },
        {
          "id": 106,
          "face": imageList.seteth,
          "crestIcon": [imageList.cichol],
          "name": "Seteth",
          "age": "??",
          "likes": ["fishing", "story writing", "Flayn"],
          "crest": "Major Crest of Cichol",
          "crestEffect": "Prevents enemy counterattacks when using combat arts.",
          "color": "darkgreen",
          "courses": ["Fishing 202", "The Teachings of Seiros", "Creative Writing"],
          "house": "Garreg Mach"
        },
        {
          "id": 107,
          "face": imageList.manuela,
          "crestIcon": [""],
          "name": "Manuela",
          "age": "??",
          "likes": ["fashion", "singing", "true love"],
          "crest": "none",
          "crestEffect": "-",
          "color": "purple",
          "courses": ["Healing with Spells", "Take to the Skies: Mastering the Pegasus and the Wyvern", "Health and Relationships for Young Adults"],
          "house": "Garreg Mach"
        },
        {
          "id": 108,
          "face": imageList.gilbert,
          "crestIcon": [""],
          "name": "Gilbert",
          "age": 56,
          "likes": ["training", "fishing", "guilt", "self-flagellation"],
          "crest": "none",
          "crestEffect": "-",
          "color": "darkorange",
          "courses": ["Shield Theory", "Advanced Armor Techniques", "Philosophy of Knighthood"],
          "house": "Garreg Mach"
        },
        {
          "id": 109,
          "face": imageList.rhea,
          "crestIcon": [imageList.seiros],
          "name": "Rhea",
          "age": "??",
          "likes": ["The Teachings of Seiros", "Sothis", "Faith"],
          "crest": "Major Crest of Seiros",
          "crestEffect": "Raises Might by 5 when using combat arts.",
          "color": "teal",
          "courses": ["Advanced Religion and Philosophy"],
          "house": "Garreg Mach"
        },
        {
          "id": 110,
          "face": imageList.anna,
          "crestIcon": [imageList.ernest],
          "name": "Anna",
          "age": 25,
          "likes": ["Money", "Secrets", "Open Trade"],
          "crest": "Major Crest of Ernest",
          "crestEffect": "Prevents enemy counterattacks when using a weapon.",
          "color": "scarlet",
          "courses": ["Economics 101", "Economics 202", "The Logistics of War", "Supply Lines and Battalion Management in Battle"],
          "house": "Garreg Mach"
        }
      ];

      const unitList = [
        {
          "id": 1,
          "name": "Byleth",
          "face": imageList.byleth,
          "house": "Garreg Mach",
          "startingLevel": 1,
          "startingClass": "commoner",
          "startingHP": 27,
          "startingStr": 13,
          "startingMag": 6,
          "startingDex": 9,
          "startingSpd": 8,
          "startingLck": 8,
          "startingDef": 6,
          "startingRes": 6,
          "startingCha": 7,
          "growthHP": 45,
          "growthStr": 45,
          "growthMag": 35,
          "growthDex": 45,
          "growthSpd": 45,
          "growthLck": 45,
          "growthDef": 35,
          "growthRes": 30,
          "growthCha": 45
        },
        {
          "id": 2,
          "name": "Edelgard",
          "face": imageList.edelgard,
          "house": "Black Eagles",
          "startingLevel": 1,
          "startingClass": "noble",
          "startingHP": 29,
          "startingStr": 13,
          "startingMag": 6,
          "startingDex": 5,
          "startingSpd": 8,
          "startingLck": 5,
          "startingDef": 6,
          "startingRes": 4,
          "startingCha": 10,
          "growthHP": 40,
          "growthStr": 55,
          "growthMag": 45,
          "growthDex": 45,
          "growthSpd": 40,
          "growthLck": 30,
          "growthDef": 35,
          "growthRes": 35,
          "growthCha": 60
        },
        {
          "id": 3,
          "name": "Hubert",
          "face": imageList.hubert,
          "house": "Black Eagles",
          "startingLevel": 1,
          "startingClass": "noble",
          "startingHP": 22,
          "startingStr": 6,
          "startingMag": 12,
          "startingDex": 6,
          "startingSpd": 7,
          "startingLck": 6,
          "startingDef": 4,
          "startingRes": 7,
          "startingCha": 6,
          "growthHP": 35,
          "growthStr": 30,
          "growthMag": 55,
          "growthDex": 45,
          "growthSpd": 45,
          "growthLck": 35,
          "growthDef": 25,
          "growthRes": 40,
          "growthCha": 35
        },
        {
          "id": 4,
          "name": "Ferdinand",
          "face": imageList.ferdinand,
          "house": "Black Eagles",
          "startingLevel": 1,
          "startingClass": "noble",
          "startingHP": 28,
          "startingStr": 8,
          "startingMag": 5,
          "startingDex": 6,
          "startingSpd": 8,
          "startingLck": 6,
          "startingDef": 6,
          "startingRes": 2,
          "startingCha": 7,
          "growthHP": 50,
          "growthStr": 45,
          "growthMag": 20,
          "growthDex": 40,
          "growthSpd": 50,
          "growthLck": 40,
          "growthDef": 35,
          "growthRes": 20,
          "growthCha": 40
        },
        {
          "id": 5,
          "name": "Bernadetta",
          "face": imageList.bernadetta,
          "house": "Black Eagles",
          "startingLevel": 1,
          "startingClass": "noble",
          "startingHP": 25,
          "startingStr": 8,
          "startingMag": 5,
          "startingDex": 7,
          "startingSpd": 7,
          "startingLck": 5,
          "startingDef": 4,
          "startingRes": 2,
          "startingCha": 6,
          "growthHP": 35,
          "growthStr": 35,
          "growthMag": 20,
          "growthDex": 55,
          "growthSpd": 50,
          "growthLck": 25,
          "growthDef": 20,
          "growthRes": 30,
          "growthCha": 35
        },
        {
          "id": 6,
          "name": "Caspar",
          "face": imageList.caspar,
          "house": "Black Eagles",
          "startingLevel": 1,
          "startingClass": "noble",
          "startingHP": 26,
          "startingStr": 9,
          "startingMag": 3,
          "startingDex": 5,
          "startingSpd": 6,
          "startingLck": 8,
          "startingDef": 6,
          "startingRes": 2,
          "startingCha": 4,
          "growthHP": 55,
          "growthStr": 45,
          "growthMag": 25,
          "growthDex": 45,
          "growthSpd": 45,
          "growthLck": 40,
          "growthDef": 30,
          "growthRes": 20,
          "growthCha": 25
        },
        {
          "id": 7,
          "name": "Dorothea",
          "face": imageList.dorothea,
          "house": "Black Eagles",
          "startingLevel": 1,
          "startingClass": "commoner",
          "startingHP": 24,
          "startingStr": 5,
          "startingMag": 11,
          "startingDex": 6,
          "startingSpd": 7,
          "startingLck": 6,
          "startingDef": 4,
          "startingRes": 7,
          "startingCha": 8,
          "growthHP": 40,
          "growthStr": 20,
          "growthMag": 40,
          "growthDex": 45,
          "growthSpd": 40,
          "growthLck": 35,
          "growthDef": 15,
          "growthRes": 35,
          "growthCha": 40
        },
        {
          "id": 8,
          "name": "Linhardt",
          "face": imageList.linhardt,
          "house": "Black Eagles",
          "startingLevel": 1,
          "startingClass": "noble",
          "startingHP": 24,
          "startingStr": 5,
          "startingMag": 10,
          "startingDex": 6,
          "startingSpd": 5,
          "startingLck": 7,
          "startingDef": 5,
          "startingRes": 9,
          "startingCha": 3,
          "growthHP": 30,
          "growthStr": 30,
          "growthMag": 45,
          "growthDex": 40,
          "growthSpd": 40,
          "growthLck": 45,
          "growthDef": 30,
          "growthRes": 45,
          "growthCha": 20
        },
        {
          "id": 9,
          "name": "Petra",
          "face": imageList.petra,
          "house": "Black Eagles",
          "startingLevel": 1,
          "startingClass": "commoner",
          "startingHP": 25,
          "startingStr": 9,
          "startingMag": 3,
          "startingDex": 7,
          "startingSpd": 10,
          "startingLck": 7,
          "startingDef": 5,
          "startingRes": 2,
          "startingCha": 6,
          "growthHP": 45,
          "growthStr": 40,
          "growthMag": 25,
          "growthDex": 50,
          "growthSpd": 60,
          "growthLck": 45,
          "growthDef": 30,
          "growthRes": 15,
          "growthCha": 35
        },
        {
          "id": 10,
          "name": "Dimitri",
          "face": imageList.dimitri,
          "house": "Blue Lions",
          "startingLevel": 1,
          "startingClass": "noble",
          "startingHP": 28,
          "startingStr": 12,
          "startingMag": 4,
          "startingDex": 7,
          "startingSpd": 7,
          "startingLck": 5,
          "startingDef": 7,
          "startingRes": 4,
          "startingCha": 9,
          "growthHP": 55,
          "growthStr": 60,
          "growthMag": 20,
          "growthDex": 50,
          "growthSpd": 50,
          "growthLck": 25,
          "growthDef": 40,
          "growthRes": 20,
          "growthCha": 55
        },
        {
          "id": 11,
          "name": "Dedue",
          "face": imageList.dedue,
          "house": "Blue Lions",
          "startingLevel": 1,
          "startingClass": "commoner",
          "startingHP": 30,
          "startingStr": 12,
          "startingMag": 2,
          "startingDex": 5,
          "startingSpd": 7,
          "startingLck": 5,
          "startingDef": 8,
          "startingRes": 1,
          "startingCha": 4,
          "growthHP": 60,
          "growthStr": 50,
          "growthMag": 15,
          "growthDex": 30,
          "growthSpd": 20,
          "growthLck": 25,
          "growthDef": 50,
          "growthRes": 10,
          "growthCha": 30
        },
        {
          "id": 12,
          "name": "Annette",
          "face": imageList.annette,
          "house": "Blue Lions",
          "startingLevel": 1,
          "startingClass": "noble",
          "startingHP": 23,
          "startingStr": 6,
          "startingMag": 11,
          "startingDex": 7,
          "startingSpd": 7,
          "startingLck": 6,
          "startingDef": 5,
          "startingRes": 4,
          "startingCha": 6,
          "growthHP": 25,
          "growthStr": 30,
          "growthMag": 50,
          "growthDex": 50,
          "growthSpd": 35,
          "growthLck": 35,
          "growthDef": 20,
          "growthRes": 30,
          "growthCha": 35
        },
        {
          "id": 13,
          "name": "Felix",
          "face": imageList.felix,
          "house": "Blue Lions",
          "startingLevel": 1,
          "startingClass": "noble",
          "startingHP": 26,
          "startingStr": 10,
          "startingMag": 5,
          "startingDex": 6,
          "startingSpd": 9,
          "startingLck": 5,
          "startingDef": 5,
          "startingRes": 3,
          "startingCha": 5,
          "growthHP": 45,
          "growthStr": 55,
          "growthMag": 30,
          "growthDex": 45,
          "growthSpd": 55,
          "growthLck": 40,
          "growthDef": 30,
          "growthRes": 20,
          "growthCha": 30
        },
        {
          "id": 14,
          "name": "Ingrid",
          "face": imageList.ingrid,
          "house": "Blue Lions",
          "startingLevel": 1,
          "startingClass": "noble",
          "startingHP": 27,
          "startingStr": 8,
          "startingMag": 6,
          "startingDex": 6,
          "startingSpd": 8,
          "startingLck": 6,
          "startingDef": 6,
          "startingRes": 8,
          "startingCha": 8,
          "growthHP": 40,
          "growthStr": 35,
          "growthMag": 35,
          "growthDex": 40,
          "growthSpd": 60,
          "growthLck": 45,
          "growthDef": 30,
          "growthRes": 40,
          "growthCha": 45
        },
        {
          "id": 15,
          "name": "Sylvain",
          "face": imageList.sylvain,
          "house": "Blue Lions",
          "startingLevel": 1,
          "startingClass": "noble",
          "startingHP": 27,
          "startingStr": 9,
          "startingMag": 5,
          "startingDex": 5,
          "startingSpd": 8,
          "startingLck": 6,
          "startingDef": 6,
          "startingRes": 2,
          "startingCha": 7,
          "growthHP": 55,
          "growthStr": 45,
          "growthMag": 30,
          "growthDex": 35,
          "growthSpd": 50,
          "growthLck": 35,
          "growthDef": 40,
          "growthRes": 25,
          "growthCha": 40
        },
        {
          "id": 16,
          "name": "Mercedes",
          "face": imageList.mercedes,
          "house": "Blue Lions",
          "startingLevel": 1,
          "startingClass": "commoner",
          "startingHP": 25,
          "startingStr": 6,
          "startingMag": 10,
          "startingDex": 6,
          "startingSpd": 8,
          "startingLck": 5,
          "startingDef": 5,
          "startingRes": 9,
          "startingCha": 8,
          "growthHP": 30,
          "growthStr": 25,
          "growthMag": 50,
          "growthDex": 45,
          "growthSpd": 40,
          "growthLck": 30,
          "growthDef": 25,
          "growthRes": 45,
          "growthCha": 40
        },
        {
          "id": 17,
          "name": "Ashe",
          "face": imageList.ashe,
          "house": "Blue Lions",
          "startingLevel": 1,
          "startingClass": "commoner",
          "startingHP": 23,
          "startingStr": 8,
          "startingMag": 5,
          "startingDex": 8,
          "startingSpd": 9,
          "startingLck": 6,
          "startingDef": 5,
          "startingRes": 6,
          "startingCha": 5,
          "growthHP": 35,
          "growthStr": 35,
          "growthMag": 25,
          "growthDex": 55,
          "growthSpd": 50,
          "growthLck": 40,
          "growthDef": 20,
          "growthRes": 35,
          "growthCha": 25
        },
        {
          "id": 18,
          "name": "Claude",
          "face": imageList.claude,
          "house": "Golden Deer",
          "startingLevel": 1,
          "startingClass": "noble",
          "startingHP": 26,
          "startingStr": 11,
          "startingMag": 5,
          "startingDex": 8,
          "startingSpd": 8,
          "startingLck": 7,
          "startingDef": 6,
          "startingRes": 4,
          "startingCha": 8,
          "growthHP": 35,
          "growthStr": 40,
          "growthMag": 25,
          "growthDex": 60,
          "growthSpd": 55,
          "growthLck": 45,
          "growthDef": 30,
          "growthRes": 25,
          "growthCha": 55
        },
        {
          "id": 19,
          "name": "Hilda",
          "face": imageList.hilda,
          "house": "Golden Deer",
          "startingLevel": 1,
          "startingClass": "noble",
          "startingHP": 29,
          "startingStr": 10,
          "startingMag": 5,
          "startingDex": 5,
          "startingSpd": 8,
          "startingLck": 6,
          "startingDef": 6,
          "startingRes": 3,
          "startingCha": 7,
          "growthHP": 50,
          "growthStr": 45,
          "growthMag": 25,
          "growthDex": 30,
          "growthSpd": 50,
          "growthLck": 35,
          "growthDef": 35,
          "growthRes": 20,
          "growthCha": 50
        },
        {
          "id": 20,
          "name": "Lorenz",
          "face": imageList.lorenz,
          "house": "Golden Deer",
          "startingLevel": 1,
          "startingClass": "noble",
          "startingHP": 28,
          "startingStr": 8,
          "startingMag": 7,
          "startingDex": 6,
          "startingSpd": 7,
          "startingLck": 5,
          "startingDef": 6,
          "startingRes": 6,
          "startingCha": 3,
          "growthHP": 55,
          "growthStr": 40,
          "growthMag": 40,
          "growthDex": 45,
          "growthSpd": 40,
          "growthLck": 25,
          "growthDef": 30,
          "growthRes": 40,
          "growthCha": 35
        },
        {
          "id": 21,
          "name": "Leonie",
          "face": imageList.leonie,
          "house": "Golden Deer",
          "startingLevel": 1,
          "startingClass": "commoner",
          "startingHP": 26,
          "startingStr": 9,
          "startingMag": 5,
          "startingDex": 8,
          "startingSpd": 9,
          "startingLck": 6,
          "startingDef": 7,
          "startingRes": 2,
          "startingCha": 7,
          "growthHP": 40,
          "growthStr": 40,
          "growthMag": 20,
          "growthDex": 55,
          "growthSpd": 60,
          "growthLck": 40,
          "growthDef": 40,
          "growthRes": 15,
          "growthCha": 40
        },
        {
          "id": 22,
          "name": "Lysithea",
          "face": imageList.lysithea,
          "house": "Golden Deer",
          "startingLevel": 1,
          "startingClass": "noble",
          "startingHP": 22,
          "startingStr": 4,
          "startingMag": 11,
          "startingDex": 7,
          "startingSpd": 7,
          "startingLck": 4,
          "startingDef": 3,
          "startingRes": 4,
          "startingCha": 5,
          "growthHP": 20,
          "growthStr": 15,
          "growthMag": 60,
          "growthDex": 60,
          "growthSpd": 50,
          "growthLck": 15,
          "growthDef": 10,
          "growthRes": 25,
          "growthCha": 25
        },
        {
          "id": 23,
          "name": "Ignatz",
          "face": imageList.ignatz,
          "house": "Golden Deer",
          "startingLevel": 1,
          "startingClass": "commoner",
          "startingHP": 25,
          "startingStr": 8,
          "startingMag": 5,
          "startingDex": 7,
          "startingSpd": 8,
          "startingLck": 8,
          "startingDef": 4,
          "startingRes": 6,
          "startingCha": 4,
          "growthHP": 35,
          "growthStr": 35,
          "growthMag": 30,
          "growthDex": 50,
          "growthSpd": 50,
          "growthLck": 55,
          "growthDef": 25,
          "growthRes": 35,
          "growthCha": 25
        },
        {
          "id": 24,
          "name": "Raphael",
          "face": imageList.raphael,
          "house": "Golden Deer",
          "startingLevel": 1,
          "startingClass": "commoner",
          "startingHP": 30,
          "startingStr": 11,
          "startingMag": 3,
          "startingDex": 5,
          "startingSpd": 6,
          "startingLck": 6,
          "startingDef": 7,
          "startingRes": 1,
          "startingCha": 4,
          "growthHP": 65,
          "growthStr": 50,
          "growthMag": 15,
          "growthDex": 35,
          "growthSpd": 15,
          "growthLck": 35,
          "growthDef": 45,
          "growthRes": 10,
          "growthCha": 25
        },
        {
          "id": 25,
          "name": "Marianne",
          "face": imageList.marianne,
          "house": "Golden Deer",
          "startingLevel": 1,
          "startingClass": "noble",
          "startingHP": 23,
          "startingStr": 5,
          "startingMag": 11,
          "startingDex": 6,
          "startingSpd": 7,
          "startingLck": 6,
          "startingDef": 4,
          "startingRes": 8,
          "startingCha": 7,
          "growthHP": 35,
          "growthStr": 20,
          "growthMag": 50,
          "growthDex": 40,
          "growthSpd": 40,
          "growthLck": 35,
          "growthDef": 15,
          "growthRes": 45,
          "growthCha": 40
        },
        {
          "id": 26,
          "name": "Yuri",
          "face": imageList.yuri,
          "house": "Ashen Wolves",
          "startingLevel": 3,
          "startingClass": "commoner",
          "startingHP": 25,
          "startingStr": 11,
          "startingMag": 7,
          "startingDex": 8,
          "startingSpd": 10,
          "startingLck": 8,
          "startingDef": 6,
          "startingRes": 8,
          "startingCha": 9,
          "growthHP": 30,
          "growthStr": 40,
          "growthMag": 35,
          "growthDex": 40,
          "growthSpd": 65,
          "growthLck": 45,
          "growthDef": 30,
          "growthRes": 35,
          "growthCha": 50
        },
        {
          "id": 27,
          "name": "Constance",
          "face": imageList.constance,
          "house": "Ashen Wolves",
          "startingLevel": 3,
          "startingClass": "noble",
          "startingHP": 23,
          "startingStr": 5,
          "startingMag": 12,
          "startingDex": 7,
          "startingSpd": 7,
          "startingLck": 4,
          "startingDef": 3,
          "startingRes": 5,
          "startingCha": 7,
          "growthHP": 20,
          "growthStr": 20,
          "growthMag": 60,
          "growthDex": 30,
          "growthSpd": 35,
          "growthLck": 15,
          "growthDef": 15,
          "growthRes": 30,
          "growthCha": 25
        },
        {
          "id": 28,
          "name": "Balthus",
          "face": imageList.balthus,
          "house": "Ashen Wolves",
          "startingLevel": 3,
          "startingClass": "noble",
          "startingHP": 29,
          "startingStr": 12,
          "startingMag": 6,
          "startingDex": 5,
          "startingSpd": 8,
          "startingLck": 3,
          "startingDef": 8,
          "startingRes": 5,
          "startingCha": 5,
          "growthHP": 50,
          "growthStr": 50,
          "growthMag": 30,
          "growthDex": 25,
          "growthSpd": 30,
          "growthLck": 20,
          "growthDef": 45,
          "growthRes": 30,
          "growthCha": 30
        },
        {
          "id": 29,
          "name": "Hapi",
          "face": imageList.hapi,
          "house": "Ashen Wolves",
          "startingLevel": 3,
          "startingClass": "commoner",
          "startingHP": 27,
          "startingStr": 7,
          "startingMag": 12,
          "startingDex": 9,
          "startingSpd": 7,
          "startingLck": 4,
          "startingDef": 4,
          "startingRes": 8,
          "startingCha": 5,
          "growthHP": 35,
          "growthStr": 35,
          "growthMag": 45,
          "growthDex": 45,
          "growthSpd": 40,
          "growthLck": 20,
          "growthDef": 15,
          "growthRes": 45,
          "growthCha": 25
        },
        {
          "id": 30,
          "name": "Cyril",
          "face": imageList.cyril,
          "house": "Garreg Mach",
          "startingLevel": 1,
          "startingClass": "commoner",
          "startingHP": 24,
          "startingStr": 7,
          "startingMag": 4,
          "startingDex": 6,
          "startingSpd": 6,
          "startingLck": 6,
          "startingDef": 5,
          "startingRes": 2,
          "startingCha": 4,
          "growthHP": 55,
          "growthStr": 40,
          "growthMag": 35,
          "growthDex": 60,
          "growthSpd": 60,
          "growthLck": 50,
          "growthDef": 30,
          "growthRes": 30,
          "growthCha": 35
        },
        {
          "id": 31,
          "name": "Shamir",
          "face": imageList.shamir,
          "house": "Garreg Mach",
          "startingLevel": 11,
          "startingClass": "sniper",
          "startingHP": 33,
          "startingStr": 17,
          "startingMag": 8,
          "startingDex": 16,
          "startingSpd": 14,
          "startingLck": 14,
          "startingDef": 12,
          "startingRes": 8,
          "startingCha": 10,
          "growthHP": 35,
          "growthStr": 40,
          "growthMag": 20,
          "growthDex": 55,
          "growthSpd": 40,
          "growthLck": 55,
          "growthDef": 20,
          "growthRes": 15,
          "growthCha": 30
        },
        {
          "id": 32,
          "name": "Catherine",
          "face": imageList.catherine,
          "house": "Garreg Mach",
          "startingLevel": 11,
          "startingClass": "swordmaster",
          "startingHP": 36,
          "startingStr": 17,
          "startingMag": 8,
          "startingDex": 12,
          "startingSpd": 16,
          "startingLck": 10,
          "startingDef": 12,
          "startingRes": 8,
          "startingCha": 7,
          "growthHP": 50,
          "growthStr": 50,
          "growthMag": 25,
          "growthDex": 40,
          "growthSpd": 55,
          "growthLck": 30,
          "growthDef": 30,
          "growthRes": 20,
          "growthCha": 25
        },
        {
          "id": 33,
          "name": "Hanneman",
          "face": imageList.hanneman,
          "house": "Garreg Mach",
          "startingLevel": 15,
          "startingClass": "mage",
          "startingHP": 32,
          "startingStr": 10,
          "startingMag": 19,
          "startingDex": 12,
          "startingSpd": 9,
          "startingLck": 9,
          "startingDef": 7,
          "startingRes": 15,
          "startingCha": 11,
          "growthHP": 40,
          "growthStr": 30,
          "growthMag": 55,
          "growthDex": 45,
          "growthSpd": 20,
          "growthLck": 35,
          "growthDef": 25,
          "growthRes": 40,
          "growthCha": 35
        },
        {
          "id": 34,
          "name": "Manuela",
          "face": imageList.manuela,
          "house": "Garreg Mach",
          "startingLevel": 15,
          "startingClass": "priest",
          "startingHP": 34,
          "startingStr": 14,
          "startingMag": 14,
          "startingDex": 12,
          "startingSpd": 16,
          "startingLck": 12,
          "startingDef": 8,
          "startingRes": 12,
          "startingCha": 15,
          "growthHP": 50,
          "growthStr": 35,
          "growthMag": 35,
          "growthDex": 40,
          "growthSpd": 60,
          "growthLck": 35,
          "growthDef": 30,
          "growthRes": 25,
          "growthCha": 50
        },
        {
          "id": 35,
          "name": "Alois",
          "face": imageList.alois,
          "house": "Garreg Mach",
          "startingLevel": 21,
          "startingClass": "warrior",
          "startingHP": 47,
          "startingStr": 24,
          "startingMag": 8,
          "startingDex": 12,
          "startingSpd": 14,
          "startingLck": 11,
          "startingDef": 17,
          "startingRes": 8,
          "startingCha": 16,
          "growthHP": 45,
          "growthStr": 45,
          "growthMag": 20,
          "growthDex": 35,
          "growthSpd": 40,
          "growthLck": 30,
          "growthDef": 40,
          "growthRes": 20,
          "growthCha": 40
        },
        {
          "id": 36,
          "name": "Anna",
          "face": imageList.anna,
          "house": "Garreg Mach",
          "startingLevel": 5,
          "startingClass": "myrmidon",
          "startingHP": 28,
          "startingStr": 8,
          "startingMag": 8,
          "startingDex": 9,
          "startingSpd": 11,
          "startingLck": 14,
          "startingDef": 6,
          "startingRes": 8,
          "startingCha": 9,
          "growthHP": 35,
          "growthStr": 35,
          "growthMag": 35,
          "growthDex": 45,
          "growthSpd": 55,
          "growthLck": 45,
          "growthDef": 30,
          "growthRes": 40,
          "growthCha": 50
        },
        {
          "id": 37,
          "name": "Seteth",
          "face": imageList.seteth,
          "house": "Garreg Mach",
          "startingLevel": 23,
          "startingClass": "wyvern rider",
          "startingHP": 47,
          "startingStr": 24,
          "startingMag": 15,
          "startingDex": 19,
          "startingSpd": 16,
          "startingLck": 12,
          "startingDef": 19,
          "startingRes": 8,
          "startingCha": 20,
          "growthHP": 50,
          "growthStr": 45,
          "growthMag": 35,
          "growthDex": 50,
          "growthSpd": 50,
          "growthLck": 25,
          "growthDef": 30,
          "growthRes": 25,
          "growthCha": 45
        },
        {
          "id": 38,
          "name": "Gilbert",
          "face": imageList.gilbert,
          "house": "Blue Lions",
          "startingLevel": 26,
          "startingClass": "fortress knight",
          "startingHP": 56,
          "startingStr": 26,
          "startingMag": 9,
          "startingDex": 22,
          "startingSpd": 8,
          "startingLck": 10,
          "startingDef": 19,
          "startingRes": 7,
          "startingCha": 20,
          "growthHP": 55,
          "growthStr": 45,
          "growthMag": 20,
          "growthDex": 45,
          "growthSpd": 30,
          "growthLck": 15,
          "growthDef": 45,
          "growthRes": 10,
          "growthCha": 35
        },
        {
          "id": 39,
          "name": "Flayn",
          "face": imageList.flayn,
          "house": "Garreg Mach",
          "startingLevel": 11,
          "startingClass": "priest",
          "startingHP": 28,
          "startingStr": 8,
          "startingMag": 15,
          "startingDex": 11,
          "startingSpd": 9,
          "startingLck": 8,
          "startingDef": 7,
          "startingRes": 16,
          "startingCha": 15,
          "growthHP": 25,
          "growthStr": 25,
          "growthMag": 55,
          "growthDex": 45,
          "growthSpd": 35,
          "growthLck": 15,
          "growthDef": 25,
          "growthRes": 50,
          "growthCha": 45
        },
        {
          "id": 40,
          "name": "Jeritza",
          "face": imageList.jeritza,
          "house": "Black Eagles",
          "startingLevel": 27,
          "startingClass": "death knight",
          "startingHP": 48,
          "startingStr": 29,
          "startingMag": 18,
          "startingDex": 15,
          "startingSpd": 25,
          "startingLck": 12,
          "startingDef": 23,
          "startingRes": 15,
          "startingCha": 10,
          "growthHP": 50,
          "growthStr": 50,
          "growthMag": 35,
          "growthDex": 35,
          "growthSpd": 60,
          "growthLck": 30,
          "growthDef": 40,
          "growthRes": 25,
          "growthCha": 25
        }
      ];

      export default {
        studentList,
        teacherList,
        unitList,
      }
